#pragma once
// Windows Header Files
#include <windows.h>
#include "hook_wrapper.h"
#include "EqFunctions.h"
//hooks
#include "commands.h"
#include "camera_mods.h"
#include "looting.h"
#include "FindPattern.h"
#include "labels.h"
#include "binds.h"
#include "raid.h"
#include "eqstr.h"
#include "chat.h"
#include "chatfilter.h"
#include "IO_ini.h"
#include "callbacks.h"
#include "item_display.h"
#include "melody.h"
#include "named_pipe.h"
#include "floating_damage.h"
#include "directx.h"
#include "nameplate.h"
#include "tellwindows.h"
// other features
#include "NPCGive.h"
#include "cycle_target.h"
#include "outputfile.h"
#include "experience.h"
#include "buff_timers.h"
#include "player_movement.h"
#include "spellsets.h"
#include "alarm.h"
#include "netstat.h"
#include "ui_manager.h"
#include "autofire.h"
#include "tooltip.h"
#include "physics.h"
#include "target_ring.h"
#include "zone_map.h"
#include "crash_handler.h"
#include "EntityManager.h"
#include "patches.h"
//#include "ZealSettings.h"
//#include "Zeal.h" 


extern HMODULE this_module;
